### ISSUE TITLE
File url on files located in folders references only parent  folder.

### ISSUE THREAD

**Issue by dballanc** [nagisa/django-bfm#1]
When trying out BFM on a folder with existing data I noticed that the clickable filename only works for files in the MEDIA_ROOT and not subfolders.

media_url set to "/static/media/"

ie browsing to:
Basic File Manager › /js/admin › Browse which is located in /static/media/js/admin

A example link:
http://192.168.1.2/static/media/DateTimeShortcuts.js

which should be:
http://192.168.1.2/static/media/js/admin/DateTimeShortcuts.js

I think the fix would be to pass in the adjusted base_url to FileSystemStorage in the django_bfm.utils.Directory class and then you could use FileSystemStorage.url() instead of "file['url'] = settings.MEDIA_URL + key"  in the collect_metadata() method.

**Comment by nagisa** [comment]
I'm already working on more functional new version for some time already. So for time being you should either apply this bugfix for yourself or wait for new version.
