### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by sehmaschine** [nagisa/django-bfm#2]
good to see another filemanager for django. but please update the docs – django-filebrowser DOES NOT use a flash-uploader!

**Comment by nagisa** [comment]
Oh, when I used it, I recall having to fiddle with something like [SWFUpload](http://www.frogx3.com/wp-content/uploads/2008/04/swfupload.jpg).

Well, but you are developer, so you know it better, mistake will be fixed with next commit.

**Comment by sehmaschine** [comment]
thanks.
